services:
  datadog:
    image: docker.io/datadog/agent:7.83.0-fips-jmx
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_SITE: ${DD_SITE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${VOLUME_DIR}/proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

