services:
  bitbucket:
    image: docker.io/atlassian/bitbucket-server:8.16.3-ubuntu-jdk17
    restart: unless-stopped
    ports:
      - "7990:7990"
      - "7999:7999"
    volumes:
      - ${VOLUME_DIR}/bitbucket_data:/var/atlassian/application-data/bitbucket

