services:
  prometheus:
    image: docker.io/prom/prometheus:v3.13.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ${VOLUME_DIR}/prometheus_3.13.1/prometheus.yml:/etc/prometheus/prometheus.yml:Z
      - ${VOLUME_DIR}/prometheus_3.13.1_data:/prometheus:Z
    restart: unless-stopped