services:
  jira:
    image: docker.io/atlassian/jira-software:10.6.0
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ${VOLUME_DIR}/jira_data:/var/atlassian/application-data/jira

